### ISSUE TITLE
Ui needs to print appropriately when there's no deadline

### ISSUE THREAD

**Issue by wish2023** [AY2021S1-CS2113T-W12-2/tp#159]
The default deadline is no deadline, and UI says "finish on No Deadline"

**Comment by daniellimws** [comment]
Is this done? From the meeting earlier it looks like it still prints "finish on No deadline"

**Comment by alstontham** [comment]
Should be fixed already:
<img width="483" alt="Screenshot 2020-11-06 at 10 37 18 PM" src="https://user-images.githubusercontent.com/46882774/98378184-a91bb480-2080-11eb-908d-275e6550128d.png">
