### ISSUE TITLE
Program crashes when timing goes past midnight

### ISSUE THREAD

**Issue by wish2023** [AY2021S1-CS2113T-W12-2/tp#191]
Some bug in TimeAllocater when you do:

`add n/uno t/2300 d/2`

**Comment by daniellimws** [comment]
Can close?

**Comment by wish2023** [comment]
Cannot. My fix clash bug was due to some issue with the method. But for this issue, it's got something to do with the TimeAllocater. Like we should have an exception if the task goes past 12am right? But the program just crashes.

**Comment by daniellimws** [comment]
When does it crash?

**Comment by wish2023** [comment]
I think can close now
